name: Pre-delete Translation

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  pull-requests: write
  statuses: write

on:
  pull_request:
    types: [closed]
    branches:
        - 'master*'
env:
 BRANCH: ${{ github.head_ref }}

jobs:
   check-translation-branch:
        runs-on: ubuntu-latest
        if: github.repository == github.vars.is_proceed
        steps:
            - name: Branch Check 🔍
              run: |
               CLEAN_BRANCH="${BRANCH//[^[:alnum:]-_]/}"
               
               echo "$CLEAN_BRANCH is valid branch for translation workflow"
              

