name: Pre-push Translation

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  pull-requests: write
  statuses: write

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
        - 'master*'
env:
 BRANCH:  ${{ github.head_ref }}

jobs:
    check-translation-branch:
        runs-on: ubuntu-latest
        if: |
          ${{github.vars.is_proceed == 'true'}}
        steps:
            - name: Branch Check 🔍
              run: |
                CLEAN_BRANCH="${BRANCH//[^[:alnum:]-_]/}"
                
                echo "$CLEAN_BRANCH is a valid branch for translation workflow"

              
